default_platform(:ios)

platform :ios do
  desc "Export ipa"
  lane :export_ipa do

    keychain_password = SecureRandom.uuid

    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
    certificate_path: "ios-build.p12",
    certificate_password: ENV["CERTIFICATE_PASSWORD"],
    keychain_name: "ios-build.keychain",
    keychain_password: keychain_password,
    log_output: true
    )
  
    install_provisioning_profile(
      path: "ios-build.mobileprovision"
    )
    disable_targets = ENV["DISABLE_TARGETS"]&.split(/,/)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: ENV["PROJECT_PATH"],
      code_sign_identity: ENV['CODE_SIGNING_IDENTITY'],
      targets: disable_targets
    )
    update_project_team(
      path: ENV["PROJECT_PATH"],
      teamid: ENV["TEAM_ID"]
    )

    if ENV["BUILD_PODS"] == 'true'
      cocoapods(
        podfile: ENV["PODS_PATH"]
      )
    end

    if ENV["WORKSPACE_PATH"] != ""
      build_app(
        workspace: ENV["WORKSPACE_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_name: ENV["OUTPUT_PATH"],
        clean: true,
        export_method: ENV["EXPORT_METHOD"]
      )
    else
      build_app(
        project: ENV["PROJECT_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_name: ENV["OUTPUT_PATH"],
        clean: true,
        export_method: ENV["EXPORT_METHOD"]
      )
    end
    
    
    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end